### PR TITLE
Lib openurl

### PR DESCRIPTION
**Pull request by stanman29**
Ok, here are my changes to the openurl.library. Please review all. I have a list of files that I did not change that will need some special review and comparison with  jens-maus/libopenurl So they can be changed too. Also we can finally be in sync with their library hopefully. 
openurl/COPYING
SUBDIRS:
cmd/Makefile
cmd/OpenURL.c
include/SDI_lib.h
library/Makefile
library/handler.c
library/util.c
locale/OpenURL.pot
locale/czech.po
locale/greek.po
locale/swedish.po
Prefs/Makefile
raPrefs/Makefile
raPrefs/browsers.c
raPrefs/ftp.c
raPrefs/version.h
tools/mkrelease.sh

### CODE REVIEW

**Comment by stanman29** [comment]
I thought I was push just my changes. I tried to update branch to current ABI_V1 Sorry about this!

**Comment by deadwood2** [comment]
Hmm, what do you want me to do with this pull request? Should I just delete it?

**Comment by stanman29** [comment]
Yes. I will try again, thanks.

**Comment by deadwood2** [comment]
Ok, I'm closing it. BTW, this is repository is a mirror of the official one, so any fixes/changes you have should go there.

**Comment by wawatok** [comment]
> Yes. I will try again, thanks.

you could fork the aros developer github repo and make puul request to it. im also wondering if we shouldnt pull the external sourca at next release and apply a diff to it using the fetch script in our mmakefile. 

i also wonder if these changes to sdi headers are in accordance with thore and jens and are going to be pushed upstream?

**Pull request closed without merging**
